[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
delegated_authority = "5Pf7TWveTKfvquduUiFv4GYoQyMxuYHF14iqnXFhrTBv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/fish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
